apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 00-master-test
spec:
  config:
    ignition:
        version: 3.2.0    
    storage:
      files:
      - contents:
          source:  test
        mode: 493
        overwrite: true
        path: /tmp
